import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useCandymachine from "../../dist/use-candymachine";
import { clusterApiUrl, Connection } from "@solana/web3.js";
import { useEffect } from "react";
import { Grid } from "@nextui-org/react";

const Home: NextPage = () => {
  const conn = new Connection(clusterApiUrl("devnet"));

  const {
    fetchCandyMachine,
    page,
    nextPage,
    prevPage,
    fetchNftsForPage,
    nfts,
    candymachineMeta,
    initialFetch,
  } = useCandymachine(conn, "ByPMt7dcfMjysaCYVT1bCxaYESZd4SCmdHtvEwiCQGCN", 4);

  useEffect(() => {
    initialFetch();
  }, []);

  console.log(nfts);
  console.log(candymachineMeta);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {nfts && nfts.length > 0 && (
        <Grid.Container gap={2}>
          {nfts.map((nft, index) => (
            <Grid xs={12} sm={6} md={4} lg={3} key={index}>
              <img src={nft.image} />
            </Grid>
          ))}
        </Grid.Container>
      )}
    </div>
  );
};

export default Home;
