import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useCandymachine from "use-candymachine";
import { useEffect } from "react";
import {
  Grid,
  Card,
  Text,
  Pagination,
  Loading,
  Container,
  Button,
  Link,
} from "@nextui-org/react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";

const Home: NextPage = () => {
  const { connection } = useConnection();
  const walletAdapter = useWallet();

  const {
    page,
    nfts,
    candymachineMeta,
    isFetchingMetadata,
    isFetchingNFTs,
    isMinting,
    changePage,
    initialFetch,
    mint,
  } = useCandymachine(
    connection,
    "AVSqKTyhvWB2gViNpaytGe3riRDjHGLEQ5q15JYKuHfT",
    4,
    walletAdapter
  );

  useEffect(() => {
    initialFetch();
  }, []);

  console.log("nfts", nfts);
  console.log("candymachienMeta", candymachineMeta);

  return (
    <div className={styles.container}>
      <Head>
        <title>Use Candymachine Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isFetchingMetadata ? (
        <Loading />
      ) : isFetchingNFTs ? (
        <Loading />
      ) : (
        (nfts?.length as number) > 0 && (
          <Grid.Container gap={8} justify="center">
            {nfts?.map((nft, index) => (
              <Grid xs key={index}>
                <Card css={{ padding: "1rem" }} variant="bordered">
                  <img src={nft.image} height={256} width={256} />
                  <Text h2 css={{ color: "$blue700", marginBottom: "1rem" }}>
                    {nft.name}
                  </Text>
                  <Text h3 css={{ color: "$accents6", marginBottom: "1rem" }}>
                    {nft.description}
                  </Text>
                </Card>
              </Grid>
            ))}
          </Grid.Container>
        )
      )}
      {isFetchingMetadata ? (
        <Loading />
      ) : (
        <Container css={{ display: "flex", flexDirection: "column" }}>
          <Pagination
            initialPage={1}
            onChange={page => changePage(page)}
            page={page}
            total={candymachineMeta?.totalPages}
          />
          <Container css={{ maxW: "300px", maxH: "100px" }}>
            {!walletAdapter.connected ? (
              <WalletMultiButton />
            ) : (
              <Button
                css={{ marginTop: "$4" }}
                onClick={async () => {
                  const nft = await mint();
                  console.log("minted nft", nft);
                }}
              >
                {isMinting ? <Loading type="points" /> : <span>Mint</span>}
              </Button>
            )}
          </Container>
        </Container>
      )}
      <Container as="footer">
        <Text>
          Made by{" "}
          <Link isExternal href="https://twitter.com/AnishDe12020">
            Anish De
          </Link>
        </Text>
        <Text>
          Source Code (GitHub) -{" "}
          <Link
            isExternal
            href="https://github.com/AnishDe12020/use-candymachine"
          >
            AnishDe12020/use-candymachine
          </Link>
        </Text>
      </Container>
    </div>
  );
};

export default Home;
